site_name: Super Skyward Towers - creator documentation
site_url: https://docs.phoenixentertainment.games/superskywardtowers-creatordocs

copyright: Copyright &copy; 2018 - 2024 Phoenix Entertainment

theme:
  name: material
  logo: Assets/images/GameIcon.png
  favicon: Assets/images/GameIcon.png

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light-blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - toc.integrate
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Phoenix_Devs